# Generated by Django 3.2.3 on 2022-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
